#!/usr/bin/env bash
# Example maintainer script.
#
# May be called in the following ways:
# new-preinst install
# new-preinst install old-version
# new-preinst upgrade old-version
#
#     The package will not yet be unpacked, so the preinst script cannot rely
#     on any files included in its package. Only essential packages and
#     pre-dependencies (Pre-Depends) may be assumed to be available.
#     Pre-dependencies will have been configured at least once, but at the
#     time the preinst is called they may only be in an unpacked or
#     "Half-Configured" state if a previous version of the pre-dependency was
#     completely configured and has not been removed since then.
#
# old-preinst abort-upgrade new-version
#
#     Called during error handling of an upgrade that failed after
#     unpacking the new package because the postrm upgrade action failed.
#     The unpacked files may be partly from the new version or partly
#     missing, so the script cannot rely on files included in the package.
#     Package dependencies may not be available. Pre-dependencies will be
#     at least unpacked following the same rules as above, except they may
#     be only "Half-Installed" if an upgrade of the pre-dependency failed.

set -e

mode=${1}
prior_version=${2:-0}

echo preinst is being run from $0 with args "$*"
echo pwd is $(pwd)
echo env is
env|grep DPKG_
