#!/usr/bin/env bash
# Example maintainer script.
#
# May be called in the following ways:
#
# prerm remove
# old-prerm upgrade new-version
# conflictor's-prerm remove in-favour package new-version
# deconfigured's-prerm deconfigure in-favour package-being-installed version
# [removing conflicting-package version]
#
#     The package whose prerm is being called will be at least
#     "Half-Installed". All package dependencies will at least be
#     "Half-Installed" and will have previously been configured and not
#     removed. If there was no error, all dependencies will at least be
#     unpacked, but these actions may be called in various error states where
#     dependencies are only "Half-Installed" due to a partial upgrade.
#
# new-prerm failed-upgrade old-version
#
#     Called during error handling when prerm upgrade fails. The new package
#     will not yet be unpacked, and all the same constraints as for preinst
#     upgrade apply.

set -e
mode=${1}

echo prerm is being run at $0 with args "$*"
echo pwd is $(pwd)
echo env is
env|grep DPKG_
